language: node_js
node_js:
- '0.11'
- '0.10'
install: npm install; bower install
deploy:
  provider: s3
  access_key_id: AKIAIIALQ2ZY23VOG3NA
  secret_access_key:
    secure: Jy6r0ZnYZoDnBv21ZEdQG/vtcHJvyFbR9HBg8uRfa0xdrHdJZRcv01pE8kOO01MGXvqjm7EW6bXX4iQ3cQRy+mruJtMEswldxcDeob2W59vianhNliAk2OaNDjmpq+ixANNSwu3rUEwII8tbc9ia4PVGZDs9NVbCkbKLEMtNf9s=
  bucket: salmondesign
  local-dir: dist
  detect_encoding: true
  on:
    repo: davidblurton/ember-behance
