language: node_js
node_js:
- '0.10'
install: npm install; bower install
script: ember build --environment production
deploy:
  edge: true
  provider: s3
  access_key_id: AKIAJ5LWZ4CET7VNWJ5Q
  secret_access_key:
    secure: GHmmBgKjnzIC5/UIdoQDLha6+2M81637g3bjAMwOtSn/mQasr//DwaEg18FsyCEKSTfxYrKbPXFnOuxP2QlSYAs8AmUdYpxUa9yyNH2TtfR4NY+uy0+8azxonRd6y+Al+5H74Gf473ZUdzMfMqg7NPVvoWM+3/Nzw9ePMjzFQjg=
  bucket: salmondesign.co
  skip_cleanup: true
  endpoint: salmondesign.co.s3-website-eu-west-1.amazonaws.com
  region: eu-west-1
  local-dir: dist
  detect_encoding: true
  cache_control: max-age=2592000
  on:
    branch: master
